apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-l41m
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: var_name
          value: test
        image: quay.io/redhat-appstudio-qe/nbe-e2e-ktvn-tenant/integ-app-lvpk/hacbs-test-project-l41m@sha256:5886542e46b03e28c03da6cf61f365a245ab798d98aaa921cd3dcbe68b5b63a5
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
